[interface]
display_name = "HelloAGENTS"
short_description = "提供 HelloAGENTS 工作流入口与命令/模块导航，并处理 ~auto/~plan/~exec/~help 等指令；当用户输入 /helloagents、$helloagents 或任何 HelloAGENTS ~命令时使用。"
icon_small = "./assets/icon-small-400px.svg"
icon_large = "./assets/icon-large.svg"
brand_color = "#6366F1"
default_prompt = ""
